name: build-ics-daily

on:
  schedule:
    - cron: "5 13 * * *"   # 09:05 AM Chile (invierno)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 selenium

      - name: Generate ICS
        env:
          SIGA_USER: ${{ secrets.SIGA_USER }}
          SIGA_PASS: ${{ secrets.SIGA_PASS }}
        run: |
          mkdir -p public
          python Inacap_to_Google_Calendar.py --weeks 2 --headless --out public/inacap_horario.ics

      - name: Commit updated ics
        run: |
          if git status --porcelain | grep -q "public/inacap_horario.ics"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add public/inacap_horario.ics
            git commit -m "update: inacap_horario.ics"
            git push
          else
            echo "No changes in ICS."
          fi

